# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 03:56
from __future__ import unicode_literals

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_floor', models.IntegerField()),
                ('placed_room', models.CharField(max_length=453)),
                ('owner', models.CharField(max_length=453)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=453)),
                ('author', models.CharField(max_length=453)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, validators=[books.models.isbn_issn_validator])),
                ('publisher', models.CharField(max_length=453)),
                ('category', models.CharField(max_length=453)),
                ('note', models.TextField(max_length=9453)),
                ('book_type', models.CharField(choices=[('BOOK', 'book'), ('SERIAL', 'serial (for magazine)')], max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookDetail'),
        ),
    ]
