# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:50
from __future__ import unicode_literals

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=453)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=453)),
                ('published_date', models.DateField()),
                ('publisher', models.CharField(max_length=453)),
                ('category', models.CharField(max_length=453)),
                ('description', models.TextField(max_length=9453)),
                ('authors', models.ManyToManyField(to='books.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ISBN_10', 'International Standard Book Number (10 digits)'), ('ISBN_13', 'International Standard Book Number (13 digits)'), ('ISSN', 'International Standard Serial Number (8 digits)')], max_length=7)),
                ('identifier', models.CharField(max_length=13, validators=[books.models.isbn_issn_validator])),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.BookDetails'),
        ),
        migrations.DeleteModel(
            name='BookDetail',
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='identifiers',
            field=models.ManyToManyField(to='books.BookIdentifier'),
        ),
    ]
