# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170409_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='description',
            field=models.TextField(max_length=9453, null=True),
        ),
    ]
